version: '3'
services:
  db:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
  web:
    build: .
    restart: always
    stdin_open: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
